--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/David-pm-pl/BetterCapes
build-by-default: true
branches:
- stable
projects:
  BetterCapes:
    path: ""
    icon: "assets/images/icon.png"
...
